export type AbilityId = "burn" | "splash" | "slow" | "lightning" | "piercing" | "push";
export type FactionId = "emberkin" | "tidekin" | "rootbound" | "stormborn" | "cloudkin" | "starborn";

export type Critter = {
  id: string;
  name: string;
  title: string;
  icon: string;
  color: string;
  cost: number;
  damage: number;
  speed: number;
  range: number;
  rarity: "Common" | "Rare" | "Epic" | "Legendary";
  skill: string;
  ability: AbilityId;
  faction: FactionId;
  tier: 1 | 2 | 3;
  starterEligible?: boolean;
  wishOnly?: boolean;
  upgradeOf?: string;
  evolutionPath?: "core" | "alternative";
  sprite?: string;
};

export type Enemy = {
  id: number;
  definitionId: string;
  step: number;
  hp: number;
  maxHp: number;
  shield: number;
  maxShield: number;
  kind: string;
  icon: string;
  boss?: boolean;
  speedMultiplier: number;
  splitInto?: number;
  splitTriggered?: boolean;
  healCooldown?: number;
  burnTicks?: number;
  burnDamage?: number;
  slowTicks?: number;
  slowFactor?: number;
};

export type Tower = { slot: number; critter: Critter; cooldown: number; sourceId: string };
export type BlessingId = "harvest" | "warden";
export type BossReward = "heartseed" | "embercore" | "starcharm";
export type AttackFx = { id: number; from: number; to: number; color: string; critterId: string };
export type CombatNumber = { id: number; cell: number; value: number; kind: "damage" | "heal"; critical?: boolean };
export type StarterStats = { runs: number; victories: number; bossesDefeated: number; wavesCleared: number; highestChapter: number };
export type BlessingCounts = Record<BlessingId, number>;
export type MetaProgress = { version: 1; owned: string[]; petals: number; stats: Record<string, StarterStats> };

export type ChapterConfig = {
  number: number;
  region: string;
  title: string;
  theme: string;
  path: number[];
  slots: number[];
  bossName: string;
  bossIcon: string;
  goalIcon: string;
  goalName: string;
};

export type EnemyCodexEntry = {
  name: string;
  title: string;
  icon: string;
  chapter: string;
  role: string;
  defence: string;
  ability: string;
  color: string;
  boss?: boolean;
};

export type RunSave = {
  version: 1 | 2 | 3 | 4;
  starterId: string;
  selected: string;
  chapter: number;
  wave: number;
  energy?: number;
  maxEnergy?: number;
  lives: number;
  dewshards: number;
  towers: { slot: number; critterId: string; sourceId?: string }[];
  runUnlocked: string[];
  guardianCopies?: Record<string, number>;
  guardianForms?: Record<string, number>;
  mapSeed?: number;
  mapVersion?: 1 | 2;
  blessings?: BlessingCounts;
  eventBuffs?: BlessingCounts;
  activeEventId?: string | null;
  recentEventIds?: string[];
  starCharmCount: number;
  nextWaveNote: string;
  eventOpen: boolean;
  recruitChoices: string[];
  bossRewardOpen: boolean;
  gameSpeed: 1 | 2;
  waveHpMultiplier: number;
  waveExtraEnemies: number;
  wavePetalBonus: number;
  runDamageMultiplier: number;
  savedAt: number;
};

export type RestoredRun = {
  starterId: string;
  selected: string;
  chapter: number;
  wave: number;
  mapSeed: number;
  mapVersion: 1 | 2;
  lives: number;
  dewshards: number;
  towers: Tower[];
  runUnlocked: string[];
  guardianCopies: Record<string, number>;
  guardianForms: Record<string, number>;
  blessings: BlessingCounts;
  activeEventId: string | null;
  recentEventIds: string[];
  starCharmCount: number;
  nextWaveNote: string;
  eventOpen: boolean;
  recruitChoices: Critter[];
  bossRewardOpen: boolean;
  gameSpeed: 1 | 2;
  waveHpMultiplier: number;
  waveExtraEnemies: number;
  wavePetalBonus: number;
  runDamageMultiplier: number;
};
